### ISSUE TITLE
Get everyone to look at GitHub Projects

### ISSUE THREAD

**Issue by klaki892** [RoboticsClubatUCF/IARC#1]
(This isnt really how issues are supposed to be used, but hey it notifies everyone.)

Simply put, everyone put a comment in this issue so that we know you are paying attention (at least once) to the GitHub and that you've been at least familiarized with the proceedings

**Comment by belmaz** [comment]
Hi

**Comment by johnmillner** [comment]
Comment

**Comment by Bootwizard** [comment]
Yo fam

**Comment by nabarcala** [comment]
Hi

**Comment by RyanHeitz** [comment]
Greetings!
